main_trial_settings_b = [
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "1",
    NID: "91",
    Topic: "皮肉",
    Vehicle: "短刀",
    NumFeatures: "3",
    F1: "人を傷つける",
    F2: "鋭い",
    F3: "心に刺さる",
    TargetDirTopic: "stimulus/images/main/n91_T.png",
    TargetDirVehicle: "stimulus/images/main/n91_V.png",
    TargetDirF1: "stimulus/images/main/n91_F1.png",
    TargetDirF2: "stimulus/images/main/n91_F2.png",
    TargetDirF3: "stimulus/images/main/n91_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "2",
    NID: "81",
    Topic: "夕日",
    Vehicle: "銅貨",
    NumFeatures: "3",
    F1: "丸い",
    F2: "輝いている",
    F3: "赤い",
    TargetDirTopic: "stimulus/images/main/n81_T.png",
    TargetDirVehicle: "stimulus/images/main/n81_V.png",
    TargetDirF1: "stimulus/images/main/n81_F1.png",
    TargetDirF2: "stimulus/images/main/n81_F2.png",
    TargetDirF3: "stimulus/images/main/n81_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "3",
    NID: "39",
    Topic: "研究",
    Vehicle: "登山",
    NumFeatures: "3",
    F1: "険しい道のり",
    F2: "達成感がある",
    F3: "苦しい",
    TargetDirTopic: "stimulus/images/main/n39_T.png",
    TargetDirVehicle: "stimulus/images/main/n39_V.png",
    TargetDirF1: "stimulus/images/main/n39_F1.png",
    TargetDirF2: "stimulus/images/main/n39_F2.png",
    TargetDirF3: "stimulus/images/main/n39_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "4",
    NID: "38",
    Topic: "蝶",
    Vehicle: "踊り子",
    NumFeatures: "3",
    F1: "美しい",
    F2: "舞う",
    F3: "華やかだ",
    TargetDirTopic: "stimulus/images/main/n38_T.png",
    TargetDirVehicle: "stimulus/images/main/n38_V.png",
    TargetDirF1: "stimulus/images/main/n38_F1.png",
    TargetDirF2: "stimulus/images/main/n38_F2.png",
    TargetDirF3: "stimulus/images/main/n38_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "5",
    NID: "63",
    Topic: "時間",
    Vehicle: "洪水",
    NumFeatures: "3",
    F1: "止められない",
    F2: "流れる",
    F3: "逆らえない",
    TargetDirTopic: "stimulus/images/main/n63_T.png",
    TargetDirVehicle: "stimulus/images/main/n63_V.png",
    TargetDirF1: "stimulus/images/main/n63_F1.png",
    TargetDirF2: "stimulus/images/main/n63_F2.png",
    TargetDirF3: "stimulus/images/main/n63_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "6",
    NID: "14",
    Topic: "暴動",
    Vehicle: "嵐",
    NumFeatures: "3",
    F1: "激しい",
    F2: "人を巻き込む",
    F3: "突然起こる",
    TargetDirTopic: "stimulus/images/main/n14_T.png",
    TargetDirVehicle: "stimulus/images/main/n14_V.png",
    TargetDirF1: "stimulus/images/main/n14_F1.png",
    TargetDirF2: "stimulus/images/main/n14_F2.png",
    TargetDirF3: "stimulus/images/main/n14_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "7",
    NID: "88",
    Topic: "批判",
    Vehicle: "メス",
    NumFeatures: "3",
    F1: "人を傷つける",
    F2: "鋭い",
    F3: "痛いところをつく",
    TargetDirTopic: "stimulus/images/main/n88_T.png",
    TargetDirVehicle: "stimulus/images/main/n88_V.png",
    TargetDirF1: "stimulus/images/main/n88_F1.png",
    TargetDirF2: "stimulus/images/main/n88_F2.png",
    TargetDirF3: "stimulus/images/main/n88_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "8",
    NID: "80",
    Topic: "煙草",
    Vehicle: "時限爆弾",
    NumFeatures: "3",
    F1: "寿命を縮める",
    F2: "危険だ",
    F3: "燃える",
    TargetDirTopic: "stimulus/images/main/n80_T.png",
    TargetDirVehicle: "stimulus/images/main/n80_V.png",
    TargetDirF1: "stimulus/images/main/n80_F1.png",
    TargetDirF2: "stimulus/images/main/n80_F2.png",
    TargetDirF3: "stimulus/images/main/n80_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "9",
    NID: "26",
    Topic: "真珠",
    Vehicle: "水滴",
    NumFeatures: "3",
    F1: "美しい",
    F2: "丸い",
    F3: "透き通っている",
    TargetDirTopic: "stimulus/images/main/n26_T.png",
    TargetDirVehicle: "stimulus/images/main/n26_V.png",
    TargetDirF1: "stimulus/images/main/n26_F1.png",
    TargetDirF2: "stimulus/images/main/n26_F2.png",
    TargetDirF3: "stimulus/images/main/n26_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "10",
    NID: "4",
    Topic: "つらら",
    Vehicle: "水晶細工",
    NumFeatures: "3",
    F1: "美しい",
    F2: "透明だ",
    F3: "繊細だ",
    TargetDirTopic: "stimulus/images/main/n4_T.png",
    TargetDirVehicle: "stimulus/images/main/n4_V.png",
    TargetDirF1: "stimulus/images/main/n4_F1.png",
    TargetDirF2: "stimulus/images/main/n4_F2.png",
    TargetDirF3: "stimulus/images/main/n4_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "11",
    NID: "48",
    Topic: "雨雲",
    Vehicle: "薄墨",
    NumFeatures: "3",
    F1: "灰色だ",
    F2: "暗い",
    F3: "黒い",
    TargetDirTopic: "stimulus/images/main/n48_T.png",
    TargetDirVehicle: "stimulus/images/main/n48_V.png",
    TargetDirF1: "stimulus/images/main/n48_F1.png",
    TargetDirF2: "stimulus/images/main/n48_F2.png",
    TargetDirF3: "stimulus/images/main/n48_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "12",
    NID: "105",
    Topic: "建物",
    Vehicle: "角砂糖",
    NumFeatures: "3",
    F1: "脆（もろ）い",
    F2: "四角い",
    F3: "白い",
    TargetDirTopic: "stimulus/images/main/n105_T.png",
    TargetDirVehicle: "stimulus/images/main/n105_V.png",
    TargetDirF1: "stimulus/images/main/n105_F1.png",
    TargetDirF2: "stimulus/images/main/n105_F2.png",
    TargetDirF3: "stimulus/images/main/n105_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "13",
    NID: "12",
    Topic: "衝撃",
    Vehicle: "電気",
    NumFeatures: "3",
    F1: "一瞬の出来事だ",
    F2: "突然来る",
    F3: "ビリビリする",
    TargetDirTopic: "stimulus/images/main/n12_T.png",
    TargetDirVehicle: "stimulus/images/main/n12_V.png",
    TargetDirF1: "stimulus/images/main/n12_F1.png",
    TargetDirF2: "stimulus/images/main/n12_F2.png",
    TargetDirF3: "stimulus/images/main/n12_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "14",
    NID: "86",
    Topic: "学校",
    Vehicle: "工場",
    NumFeatures: "3",
    F1: "人がたくさんいる",
    F2: "画一的だ",
    F3: "生産する",
    TargetDirTopic: "stimulus/images/main/n86_T.png",
    TargetDirVehicle: "stimulus/images/main/n86_V.png",
    TargetDirF1: "stimulus/images/main/n86_F1.png",
    TargetDirF2: "stimulus/images/main/n86_F2.png",
    TargetDirF3: "stimulus/images/main/n86_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "15",
    NID: "74",
    Topic: "子猫",
    Vehicle: "王女",
    NumFeatures: "3",
    F1: "かわいい",
    F2: "大切にされている",
    F3: "わがままだ",
    TargetDirTopic: "stimulus/images/main/n74_T.png",
    TargetDirVehicle: "stimulus/images/main/n74_V.png",
    TargetDirF1: "stimulus/images/main/n74_F1.png",
    TargetDirF2: "stimulus/images/main/n74_F2.png",
    TargetDirF3: "stimulus/images/main/n74_F3.png"
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "16",
    NID: "16",
    Topic: "楽譜",
    Vehicle: "暗号",
    NumFeatures: "1",
    F1: "わからない",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n16_T.png",
    TargetDirVehicle: "stimulus/images/main/n16_V.png",
    TargetDirF1: "stimulus/images/main/n16_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "17",
    NID: "83",
    Topic: "煙突",
    Vehicle: "石碑",
    NumFeatures: "1",
    F1: "まっすぐ立っている",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n83_T.png",
    TargetDirVehicle: "stimulus/images/main/n83_V.png",
    TargetDirF1: "stimulus/images/main/n83_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "18",
    NID: "75",
    Topic: "空",
    Vehicle: "鏡",
    NumFeatures: "1",
    F1: "澄（す）んでいる",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n75_T.png",
    TargetDirVehicle: "stimulus/images/main/n75_V.png",
    TargetDirF1: "stimulus/images/main/n75_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "19",
    NID: "9",
    Topic: "子供",
    Vehicle: "天使",
    NumFeatures: "1",
    F1: "かわいい",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n9_T.png",
    TargetDirVehicle: "stimulus/images/main/n9_V.png",
    TargetDirF1: "stimulus/images/main/n9_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "20",
    NID: "96",
    Topic: "柿",
    Vehicle: "ちょうちん",
    NumFeatures: "1",
    F1: "丸い",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n96_T.png",
    TargetDirVehicle: "stimulus/images/main/n96_V.png",
    TargetDirF1: "stimulus/images/main/n96_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "21",
    NID: "58",
    Topic: "デモ",
    Vehicle: "雪崩（なだれ）",
    NumFeatures: "1",
    F1: "止められない",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n58_T.png",
    TargetDirVehicle: "stimulus/images/main/n58_V.png",
    TargetDirF1: "stimulus/images/main/n58_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "22",
    NID: "61",
    Topic: "疑惑",
    Vehicle: "腫瘍（しゅよう）",
    NumFeatures: "1",
    F1: "ふくれあがる",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n61_T.png",
    TargetDirVehicle: "stimulus/images/main/n61_V.png",
    TargetDirF1: "stimulus/images/main/n61_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "23",
    NID: "45",
    Topic: "教育",
    Vehicle: "階段",
    NumFeatures: "1",
    F1: "段階を踏んでいく",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n45_T.png",
    TargetDirVehicle: "stimulus/images/main/n45_V.png",
    TargetDirF1: "stimulus/images/main/n45_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "24",
    NID: "62",
    Topic: "微風",
    Vehicle: "吐息",
    NumFeatures: "1",
    F1: "優しい",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n62_T.png",
    TargetDirVehicle: "stimulus/images/main/n62_V.png",
    TargetDirF1: "stimulus/images/main/n62_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "25",
    NID: "77",
    Topic: "山",
    Vehicle: "王様",
    NumFeatures: "1",
    F1: "大きい",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n77_T.png",
    TargetDirVehicle: "stimulus/images/main/n77_V.png",
    TargetDirF1: "stimulus/images/main/n77_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "26",
    NID: "52",
    Topic: "仕事",
    Vehicle: "牢獄（ろうごく）",
    NumFeatures: "1",
    F1: "つらい",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n52_T.png",
    TargetDirVehicle: "stimulus/images/main/n52_V.png",
    TargetDirF1: "stimulus/images/main/n52_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "27",
    NID: "89",
    Topic: "愛",
    Vehicle: "季節",
    NumFeatures: "1",
    F1: "移り変わる",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n89_T.png",
    TargetDirVehicle: "stimulus/images/main/n89_V.png",
    TargetDirF1: "stimulus/images/main/n89_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "28",
    NID: "85",
    Topic: "利息",
    Vehicle: "年貢",
    NumFeatures: "1",
    F1: "払わなければならない",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n85_T.png",
    TargetDirVehicle: "stimulus/images/main/n85_V.png",
    TargetDirF1: "stimulus/images/main/n85_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "29",
    NID: "110",
    Topic: "椿（つばき）",
    Vehicle: "ひとだま",
    NumFeatures: "1",
    F1: "丸い",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n110_T.png",
    TargetDirVehicle: "stimulus/images/main/n110_V.png",
    TargetDirF1: "stimulus/images/main/n110_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "30",
    NID: "32",
    Topic: "審判",
    Vehicle: "天秤",
    NumFeatures: "1",
    F1: "公平だ",
    F2: "",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n32_T.png",
    TargetDirVehicle: "stimulus/images/main/n32_V.png",
    TargetDirF1: "stimulus/images/main/n32_F1.png",
    TargetDirF2: "",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "31",
    NID: "112",
    Topic: "雑巾",
    Vehicle: "亀",
    NumFeatures: "2",
    F1: "臭い",
    F2: "汚い",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n112_T.png",
    TargetDirVehicle: "stimulus/images/main/n112_V.png",
    TargetDirF1: "stimulus/images/main/n112_F1.png",
    TargetDirF2: "stimulus/images/main/n112_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "32",
    NID: "20",
    Topic: "不安",
    Vehicle: "濃霧（のうむ）",
    NumFeatures: "2",
    F1: "先が見えない",
    F2: "晴れない",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n20_T.png",
    TargetDirVehicle: "stimulus/images/main/n20_V.png",
    TargetDirF1: "stimulus/images/main/n20_F1.png",
    TargetDirF2: "stimulus/images/main/n20_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "33",
    NID: "55",
    Topic: "理論",
    Vehicle: "建物",
    NumFeatures: "2",
    F1: "積み重ねる",
    F2: "組み立てる",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n55_T.png",
    TargetDirVehicle: "stimulus/images/main/n55_V.png",
    TargetDirF1: "stimulus/images/main/n55_F1.png",
    TargetDirF2: "stimulus/images/main/n55_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "34",
    NID: "17",
    Topic: "希望",
    Vehicle: "灯火",
    NumFeatures: "2",
    F1: "消える",
    F2: "明るい",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n17_T.png",
    TargetDirVehicle: "stimulus/images/main/n17_V.png",
    TargetDirF1: "stimulus/images/main/n17_F1.png",
    TargetDirF2: "stimulus/images/main/n17_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "35",
    NID: "73",
    Topic: "運命",
    Vehicle: "通り魔",
    NumFeatures: "2",
    F1: "予測できない",
    F2: "恐ろしい",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n73_T.png",
    TargetDirVehicle: "stimulus/images/main/n73_V.png",
    TargetDirF1: "stimulus/images/main/n73_F1.png",
    TargetDirF2: "stimulus/images/main/n73_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "36",
    NID: "33",
    Topic: "沈黙",
    Vehicle: "海底",
    NumFeatures: "2",
    F1: "静かだ",
    F2: "暗い",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n33_T.png",
    TargetDirVehicle: "stimulus/images/main/n33_V.png",
    TargetDirF1: "stimulus/images/main/n33_F1.png",
    TargetDirF2: "stimulus/images/main/n33_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "37",
    NID: "59",
    Topic: "霧（きり）",
    Vehicle: "ベール",
    NumFeatures: "2",
    F1: "白い",
    F2: "覆う",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n59_T.png",
    TargetDirVehicle: "stimulus/images/main/n59_V.png",
    TargetDirF1: "stimulus/images/main/n59_F1.png",
    TargetDirF2: "stimulus/images/main/n59_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "38",
    NID: "5",
    Topic: "激怒",
    Vehicle: "噴火",
    NumFeatures: "2",
    F1: "突然起こる",
    F2: "勢いが激しい",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n5_T.png",
    TargetDirVehicle: "stimulus/images/main/n5_V.png",
    TargetDirF1: "stimulus/images/main/n5_F1.png",
    TargetDirF2: "stimulus/images/main/n5_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "39",
    NID: "99",
    Topic: "眼",
    Vehicle: "湖",
    NumFeatures: "2",
    F1: "美しい",
    F2: "澄（す）んでいる",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n99_T.png",
    TargetDirVehicle: "stimulus/images/main/n99_V.png",
    TargetDirF1: "stimulus/images/main/n99_F1.png",
    TargetDirF2: "stimulus/images/main/n99_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "40",
    NID: "117",
    Topic: "唇（くちびる）",
    Vehicle: "蛭（ひる）",
    NumFeatures: "2",
    F1: "気持ち悪い",
    F2: "分厚い",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n117_T.png",
    TargetDirVehicle: "stimulus/images/main/n117_V.png",
    TargetDirF1: "stimulus/images/main/n117_F1.png",
    TargetDirF2: "stimulus/images/main/n117_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "41",
    NID: "2",
    Topic: "笑顔",
    Vehicle: "花",
    NumFeatures: "2",
    F1: "美しい",
    F2: "明るい",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n2_T.png",
    TargetDirVehicle: "stimulus/images/main/n2_V.png",
    TargetDirF1: "stimulus/images/main/n2_F1.png",
    TargetDirF2: "stimulus/images/main/n2_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "42",
    NID: "19",
    Topic: "心臓",
    Vehicle: "時計",
    NumFeatures: "2",
    F1: "一定のリズムを刻む",
    F2: "正確だ",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n19_T.png",
    TargetDirVehicle: "stimulus/images/main/n19_V.png",
    TargetDirF1: "stimulus/images/main/n19_F1.png",
    TargetDirF2: "stimulus/images/main/n19_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "43",
    NID: "119",
    Topic: "麦畑",
    Vehicle: "海",
    NumFeatures: "2",
    F1: "波打つ",
    F2: "広い",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n119_T.png",
    TargetDirVehicle: "stimulus/images/main/n119_V.png",
    TargetDirF1: "stimulus/images/main/n119_F1.png",
    TargetDirF2: "stimulus/images/main/n119_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "44",
    NID: "72",
    Topic: "香水",
    Vehicle: "花束",
    NumFeatures: "2",
    F1: "良い香りがする",
    F2: "華やかだ",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n72_T.png",
    TargetDirVehicle: "stimulus/images/main/n72_V.png",
    TargetDirF1: "stimulus/images/main/n72_F1.png",
    TargetDirF2: "stimulus/images/main/n72_F2.png",
    TargetDirF3: ""
  },
  {
    TrialType: "Main",
    SetType: "B",
    FinStimID: "45",
    NID: "95",
    Topic: "礼儀",
    Vehicle: "檻（おり）",
    NumFeatures: "2",
    F1: "堅苦しい",
    F2: "縛られる",
    F3: "",
    TargetDirTopic: "stimulus/images/main/n95_T.png",
    TargetDirVehicle: "stimulus/images/main/n95_V.png",
    TargetDirF1: "stimulus/images/main/n95_F1.png",
    TargetDirF2: "stimulus/images/main/n95_F2.png",
    TargetDirF3: ""
  }
]